/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedLine: typeof import('./src/components/AnimatedLine.vue')['default']
    ArtistBody: typeof import('./src/components/ArtistBody.vue')['default']
    ArtistName: typeof import('./src/components/ArtistName.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ItemsLayout: typeof import('./src/components/ItemsLayout.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PostCard: typeof import('./src/components/posts/PostCard.vue')['default']
    Posts: typeof import('./src/components/posts/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestSection: typeof import('./src/components/TestSection.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new_236e83bd1fdc08a1155825e1ed5be536/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UCarousel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new_236e83bd1fdc08a1155825e1ed5be536/node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
  }
}
